packages:
  - .
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@fallow-cli/darwin-arm64@2.88.3'
  - '@fallow-cli/darwin-x64@2.88.3'
  - '@fallow-cli/linux-arm64-gnu@2.88.3'
  - '@fallow-cli/linux-arm64-musl@2.88.3'
  - '@fallow-cli/linux-x64-gnu@2.88.3'
  - '@fallow-cli/linux-x64-musl@2.88.3'
  - '@fallow-cli/win32-arm64-msvc@2.88.3'
  - '@fallow-cli/win32-x64-msvc@2.88.3'
  - '@mui/x-data-grid@9.4.0'
  - '@mui/x-date-pickers@9.4.0'
  - '@mui/x-virtualizer@9.0.0-alpha.8'
  - fallow@2.88.3
